//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthWholesaler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date_Ordered { get; set; }
        public Nullable<System.DateTime> Date_Returned { get; set; }
        public int ProductId { get; set; }
        public int CompanyId { get; set; }
        public int OffersId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual Product Product { get; set; }
    }
}
